// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: dZbt1US7JmqH4GfLm2r4uE
import * as React from "react";
import { ParallaxProviderWrapper } from "@plasmicpkgs/react-scroll-parallax";

export default function GlobalContextsProvider(props) {
  const { children, parallaxProviderWrapperProps } = props;
  return (
    <ParallaxProviderWrapper
      {...parallaxProviderWrapperProps}
      scrollAxis={
        parallaxProviderWrapperProps &&
        "scrollAxis" in parallaxProviderWrapperProps
          ? parallaxProviderWrapperProps.scrollAxis
          : undefined
      }
    >
      {children}
    </ParallaxProviderWrapper>
  );
}
